# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-20 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181020_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='anthor',
            new_name='author',
        ),
    ]
